### ISSUE TITLE
Extension doesn't work on youtube or when focus is on a form field

### ISSUE THREAD

**Issue by tarach** [KennethSundqvist/key-jump-chrome-extension#54]
Love your extension exactly what I was looking for.
Unfortunately it doesn't work for me on youtube or when a form field is highlighted. Any suggestions?

**Comment by EvilOatmeal** [comment]
Hey, thanks! And thank you for reporting this issue.

It's intentional that the extension doesn't activate when you have a form field focused, because otherwise you can't type the default activation key `,` in text fields on any page. I've created a new issue to add an option for this behaviour: https://github.com/EvilOatmeal/key-jump-chrome-extension/issues/55. A workaround until that option is available is to either press `tab` to change focus out of the field, or use an extension that lets you clear the focus when you press `escape` or something like that.

I will investigate why it doesn't work on YouTube over the weekend and try to get a fix out.

**Comment by KennethSundqvist** [comment]
A new version is out (5.1.0) which fixes the problem with YouTube.

Sorry for the long delay!
